develop: rearrange the sequence, 0x for common util, 1x for apps, 9x for crond etc

diff --git a/etc/runit/p1 b/etc/runit/p1
--- a/etc/runit/p1
+++ b/etc/runit/p1
@@ -3,10 +3,8 @@ set -e
 
 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
 
-# Save all environment variables sent to container
-export > /etc/envvars
-
 echo "Starting one-time pre-service init scripts in /etc/preinit.d"
+
 for _script in /etc/preinit.d/*; do
     if [ -x "${_script}" ] && [ ! -e /etc/runit/stopall ]; then
         echo >&2 "*** Running: ${_script}"
@@ -19,8 +17,14 @@ for _script in /etc/preinit.d/*; do
 				exit ${retval}
 			fi
         fi
+    else
+		echo >&2 "*** Failed to run: ${_script}. Please chmod +x ${_script}"
     fi
 done
+
+# Save all environment variables sent to container
+# Including env vars being exported from preinit.d scripts
+export > /etc/envvars
 
 touch /etc/runit/runit
 touch /etc/runit/stopit
diff --git a/etc/runit/p3 b/etc/runit/p3
--- a/etc/runit/p3
+++ b/etc/runit/p3
@@ -13,12 +13,15 @@ sv -w196 force-stop /etc/service/*
 sv exit /etc/service/*
 
 echo "Running post-service clearing scripts in /etc/postclr.d"
+
 for _script in /etc/postclr.d/*; do
     if [ -x ${_script} ]; then
         echo >&2 "*** Running: ${_script}"
         ${_script}
+    else
+		echo >&2 "*** Failed to run: ${_script}. Please chmod +x ${_script}"
     fi
 done
-
+\rm -f /etc/envvars /etc/runit/stopall
 echo 'Shutting down the container ... ...'
 test -x /etc/init.d/rc && /etc/init.d/rc ${LAST}
