develop: refactorer the preinit.d and entrypoint to enhance the usability

diff --git a/etc/runit/p1 b/etc/runit/p1
--- a/etc/runit/p1
+++ b/etc/runit/p1
@@ -1,7 +1,7 @@
 #!/bin/sh
 set -e
 
-PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+#PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin;
 
 echo "Starting one-time pre-service init scripts in /etc/preinit.d"
 
@@ -11,23 +11,19 @@ for _script in /etc/preinit.d/*; do
         ${_script}
         retval=$?
         if [ ${retval} != 0 ]; then
-			echo >&2 "*** Failed with return value: $?"
-			if [ ${SCRIPT_FAILMODE} -eq 1 ]; then
-				touch /etc/runit/stopall
-				exit ${retval}
-			fi
+            echo >&2 "*** Failed with return value: $?"
+            if [ ${SCRIPT_FAILMODE} -eq 1 ]; then
+                touch /etc/runit/stopall
+                exit ${retval}
+            fi
         fi
     else
-		echo >&2 "*** Failed to run: ${_script}. Please chmod +x ${_script}"
+        echo >&2 "*** Failed to run: ${_script}. Please chmod +x ${_script}"
     fi
 done
 
-# Save all environment variables sent to container
-# Including env vars being exported from preinit.d scripts
-export > /etc/envvars
-
 touch /etc/runit/runit
 touch /etc/runit/stopit
-chmod 0 /etc/runit/stopit 
+chmod 0 /etc/runit/stopit
 
-unset _script 
+unset _script
diff --git a/etc/runit/p3 b/etc/runit/p3
--- a/etc/runit/p3
+++ b/etc/runit/p3
@@ -1,27 +1,32 @@
 #!/bin/sh
 set -e
 
-PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+#PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
 
 exec 2>&1
 
 LAST=0
 test -x /etc/runit/reboot && LAST=6
 
-echo 'Forcing all services in /etc/service to stop ... ...'
-sv -w196 force-stop /etc/service/*
-sv exit /etc/service/*
+echo "Forcing all services in /etc/service to stop ... ..."
+# First try to stop services by the reverse order
+for _srv in $(ls -r1 /etc/service); do
+    sv force-stop ${_srv}
+done
+# Then force stop all service if there any remains
+sv -w196 force-stop /etc/service/* 2>/dev/null
 
 echo "Running post-service clearing scripts in /etc/postclr.d"
-
 for _script in /etc/postclr.d/*; do
     if [ -x ${_script} ]; then
         echo >&2 "*** Running: ${_script}"
         ${_script}
     else
-		echo >&2 "*** Failed to run: ${_script}. Please chmod +x ${_script}"
+        echo >&2 "*** Failed to run: ${_script}. Please chmod +x ${_script}"
     fi
 done
-\rm -f /etc/envvars /etc/runit/stopall
-echo 'Shutting down the container ... ...'
+
+\rm -f /etc/runit/stopall
 test -x /etc/init.d/rc && /etc/init.d/rc ${LAST}
+
+unset _script _srv
